#!groovy

def PROJECT_NAME = "spring-postgresql-demo"

pipeline {
    agent any
    stages {
        stage('Checkout GitHub') {
            steps {
                git changelog: true, poll: true,
                        branch: 'h2',
                        url: "https://github.com/garystafford/${PROJECT_NAME}"
            }
        }
        stage('Create GKE Cluster') {
            steps {
                dir('kubernetes/') {
                    sh 'sh ./part1B-get-cluster-creds.sh'
                }
            }
        }
    }
}
