#!groovy

def ACCOUNT = "garystafford"
def PROJECT_NAME = "spring-postgresql-demo"
def ENVIRONMENT = "dev" // assumes 'api.dev.voter-demo.com' reachable

pipeline {
    agent any
    stages {
        stage('Checkout SCM') {
            steps {
                git changelog: true, poll: false,
                        branch: 'master',
                        url: "https://github.com/${ACCOUNT}/${PROJECT_NAME}"
            }
        }
        stage('Smoke Test') {
            steps {
                dir('postman') {
                    nodejs('nodejs') {
                        sh "sh ./newman-smoke-tests-${ENVIRONMENT}.sh"
                    }
                    junit '**/newman/*.xml'
                }
            }
        }
        stage('Integration Tests') {
            steps {
                dir('postman') {
                    nodejs('nodejs') {
                        sh "sh ./newman-integration-tests-${ENVIRONMENT}.sh"
                    }
                    junit '**/newman/*.xml'
                }
            }
        }
    }
}
