#!groovy

def PROJECT_NAME = "spring-postgresql-demo"

pipeline {
    agent any
    stages {
        stage('Checkout GitHub') {
            steps {
                git changelog: true, poll: true,
                        branch: 'h2',
                        url: "https://github.com/garystafford/${PROJECT_NAME}"
            }
        }
        stage('Get Cluster Creds') {
            steps {
                dir('kubernetes') {
                    sh 'sh ./part1b-get-cluster-creds.sh'
                }
            }
        }
        stage('Build Environments') {
            steps {
                dir('kubernetes') {
                    sh 'sh ./part2-create-environments.sh'
                }
            }
        }
        stage('Deploy Postgres to dev') {
            steps {
                dir('kubernetes') {
                    sh 'sh ./deploy-postgres-local.sh'
                }
            }
        }
        stage('Deploy Election v1') {
            environment { // get cluster ip ranges for deploy script
                IP_RANGE = sh(returnStdout: true, script: 'sh ./kubernetes/get-cluster-ip-ranges.sh')
            }
            steps {
                dir('kubernetes') {
                    sh 'env | sort'
                    sh 'sh ./part3a-deploy-v1-dev.sh'
                }
            }
        }
    }
}
