#!groovy

def PROJECT_NAME = "spring-postgresql-demo"

pipeline {
    agent any
    stages {
        stage('Checkout GitHub') {
            steps {
                git changelog: true, poll: true,
                        branch: 'h2',
                        url: "https://github.com/garystafford/${PROJECT_NAME}"
            }
        }
        stage('Build Environments') {
            steps {
                dir('kubernetes') {
                    sh 'sh ./part2-create-environments.sh'
                }
            }
        }
        stage('Get Cluster CIDRs') {
            steps {
                dir('kubernetes') {
                    sh 'export IP_RANGES=$(sh ./get-cluster-ip-ranges.sh)'
                }
            }
        }
        stage('Deploy Postgres to dev') {
            steps {
                dir('kubernetes') {
                    sh 'sh ./deploy-postgres-local.sh'
                }
            }
        }
        stage('Deploy Election v1') {
            steps {
                dir('kubernetes') {
                    sh 'sh ./part3-deploy-v1-all-envs.sh'
                }
            }
        }
    }
}
