#!groovy

def ARTIFACT_PREFIX = "spring-postgresql-demo"
def ARTIFACT_VERSION = "2.1"
def ARTIFACT_NAME = "${ARTIFACT_PREFIX}-${ARTIFACT_VERSION}.${BUILD_NUMBER}"

pipeline {
 agent any
 tools {
  gradle 'gradle'
 }
 stages {
  stage('Checkout GitHub') {
   steps {
    git changelog: true, poll: true,
     branch: 'h2',
     url: "https://github.com/garystafford/${ARTIFACT_PREFIX}"
   }
  }
  stage('Build') {
   steps {
    sh 'gradle clean build -x test'
   }
  }
  stage('Unit Test') {
   steps {
     withEnv(['SPRING_DATASOURCE_URL=jdbc:h2:file:~/elections']) {
       sh 'gradle cleanTest test'
     }
     junit '**/build/test-results/test/*.xml'
   }
  }
  stage('SonarQube Analysis') {
   steps {
    withSonarQubeEnv('Local SonarQube') {
     sh "gradle sonarqube -Dsonar.projectName=${ARTIFACT_PREFIX}"
    }
   }
  }
  stage('Archive Artifact') {
    steps {
        sh "mv build/libs/*.jar build/libs/${ARTIFACT_NAME}.jar"
        archiveArtifacts 'build/libs/*.jar'
    }
  }
  stage('Publish Artifact') {
   steps {
    withCredentials([string(credentialsId: 'GIT_TOKEN', variable: 'GIT_TOKEN')]) {
        dir('build/libs/') {
             sh "git init \
             && git config user.name \"jenkins-ci\" \
             && git config user.email \"jenkins-ci@jenkins-ci.com\" \
             && git add *.jar \
             && git commit -m \"Publish ${ARTIFACT_NAME}.jar\" \
             && git push --force --quiet --progress \
                \"https://x-access-token:${GIT_TOKEN}@github.com/garystafford/${ARTIFACT_PREFIX}.git\" \
                master:build-artifacts-gke"
      }
    }
   }
  }
 }
}
