#!groovy

pipeline {
 agent any
 tools {
  gradle 'gradle'
 }
 stages {
  stage('Checkout SCM') {
   steps {
    git changelog: true, poll: true,
     branch: 'master',
     url: 'https://github.com/garystafford/spring-postgresql-demo'
   }
  }
  stage('Build JAR') {
   steps {
    sh 'gradle clean build -x test'
   }
  }
  stage('Unit Test') {
   steps {
     withEnv(['SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/elections',
              'SPRING_LIQUIBASE_ENABLED=false']) {
       sh 'gradle cleanTest test'
     }
   }
  }
  stage('SonarQube Analysis') {
   steps {
    withSonarQubeEnv('Local SonarQube') {
     sh 'gradle sonarqube -Dsonar.projectName=spring-postgresql-demo'
    }
   }
  }
  stage('Publish to GitHub') {
   steps {
    withCredentials([string(credentialsId: 'GIT_TOKEN', variable: 'GIT_TOKEN')]) {
     sh 'cd build/libs \
         && git init \
         && git config user.name "jenkins-ci" \
         && git config user.email "jenkins-ci@jenkins-ci.com" \
         && git add *.jar \
         && git commit -m "Deploy JAR build artifacts to GitHub" \
         && git push --force --quiet --progress \
            "https://x-access-token:$GIT_TOKEN@github.com/garystafford/spring-postgresql-demo.git" \
            master:build-artifacts-gke'
    }
   }
  }
 }
}
